apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    service: pmt-pmt-env
  name: pmt-env
data:
  acceptEULA: "YES"
  datastoreHost: pmt
  datastorePort: "9200"
  startDatastore: "true"
  startPMT: "true"
  # note that the PMT image has no env var for setting username/password. Defaults are admin and admin.