apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmt
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pmt
  strategy: {}
  template:
    metadata:
      labels:
        service: pmt
    spec:
      initContainers:
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers:
      - name: pmt
        image: adobecoldfusion/pmt2021:2021.0.2
        imagePullPolicy: ""
        ports:
        - containerPort: 9101
        - containerPort: 9200
        env:
        - name: acceptEULA
          valueFrom:
            configMapKeyRef:
              key: acceptEULA
              name: pmt-env
        - name: datastoreHost
          valueFrom:
            configMapKeyRef:
              key: datastoreHost
              name: pmt-env
        - name: datastorePort
          valueFrom:
            configMapKeyRef:
              key: datastorePort
              name: pmt-env
        - name: startDatastore
          valueFrom:
            configMapKeyRef:
              key: startDatastore
              name: pmt-env
        - name: startPMT
          valueFrom:
            configMapKeyRef:
              key: startPMT
              name: pmt-env
        #livenessProbe:
        #  exec:
        #    command:
        #    - curl -f http://localhost:9101/
        #  periodSeconds: 60
        #  timeoutSeconds: 3
        volumeMounts:
        - name: logs
          mountPath: /opt/coldfusionperformancemonitoringtoolset/datastore/logs/
        resources: {}
      - name: tail-logs
        image: busybox
        command:
        - sh
        - -c
        - tail -f /opt/coldfusionperformancemonitoringtoolset/datastore/logs/elasticsearch.log
        volumeMounts:
        - name: logs
          mountPath: /opt/coldfusionperformancemonitoringtoolset/datastore/logs/
      volumes:
        - name: logs
          emptyDir: {}
      restartPolicy: Always
      serviceAccountName: ""
      # volumes: null
status: {}
