version: "3" 
services:
     
    coldfusion:
        container_name: coldfusion
        image: eaps-docker-coldfusion.bintray.io/cf/coldfusion:2018.0.10
        ports:
        - "8500:8500"
        volumes:
        - ./app:/app
        env_file:
        - coldfusion.env
        healthcheck:
           test: curl -f http://localhost:8500/ 
           interval: 1m
           timeout: 3s
        networks:
        - webnet
 
    pmt: 
       # default username and password are admin/admin 
       container_name: pmt
       image: eaps-docker-coldfusion.bintray.io/cf/pmt:2018.0.2
       depends_on:
       - coldfusion
       ports:
       - "9101:9101"
       - "9200:9200"
       env_file:
       - pmt.env
       volumes:
       - ./datastorelogs/:/opt/coldfusionperformancemonitoringtoolset/datastore/logs/
       healthcheck:
          test: curl -f http://localhost:9101/  
          interval: 1m
          timeout: 3s
       networks: 
       - webnet
 
networks:
    webnet: