version: "3" 
services:
    coldfusion: 
        image: eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest
        expose:
            - "8500"
        environment:
            - acceptEULA=YES
            - password=123
    nginx:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - coldfusion
        ports:
        - "4000:4000"
    